

logging.level.org.springframework=ERROR

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/testAuction
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
logging.level.org.springframework.security=DEBUG


server.address=0.0.0.0
server.port=${PORT:80}

huggingface.api.url=https://api-inference.huggingface.co/models/distilgpt2
huggingface.api.key=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

#huggingface.api.url=https://api-inference.huggingface.co/models/gpt2-medium
#huggingface.api.url=https://api-inference.huggingface.co/models/distilgpt2
#huggingface.api.url=https://api-inference.huggingface.co/models/gpt2-large - too slow answer
#https://api-inference.huggingface.co/models/EleutherAI/gpt-neo-125M - too slow answer